### PR TITLE
make unit test script portable

### PR DESCRIPTION
**Pull request by mimoo**
this was not working on mac previously

### CODE REVIEW

**Comment by mimoo** [comment]
mmm, I still get an error which seems weird:

```
/Users/david/Work/mina/src/lib/snarky_js_bindings/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:7508
         throw err;
         ^

Error: Cannot prove execution of myMethod(), no prover found. Try calling `await MyContract.compile()` first, this will cache provers in the background.
    at addProof (file:///Users/david/Work/mina/src/lib/snarky_js_bindings/snarkyjs/dist/node/lib/account_update.js:1220:19)
    at addMissingProofs (file:///Users/david/Work/mina/src/lib/snarky_js_bindings/snarkyjs/dist/node/lib/account_update.js:1253:52)
    at Object.prove (file:///Users/david/Work/mina/src/lib/snarky_js_bindings/snarkyjs/dist/node/lib/mina.js:142:50)
    at file:///Users/david/Work/mina/src/lib/snarky_js_bindings/snarkyjs/dist/node/lib/circuit_value.unit-test.js:139:10
```

**Comment by mimoo** [comment]
after running `npm i && num run build` all the tests in dist have disappeared :D confused

**Comment by mitschabaude** [comment]
> after running `npm i && num run build` all the tests in dist have disappeared :D confused

That's expected, npm run build cleans up the folder and doesn't build the unit tests. To build & run one test we have
`./run path/to/test`

**Comment by mimoo** [comment]
(not sure why CI is not passing)

**Comment by Trivo25** [comment]
something is wrong with the Berkeley live integration test - not your fault :D

**Review by mitschabaude — APPROVED** [review]
Looks like it works. Thanks @mimoo!

**Pull request merged**
